#[derive(Clone, PartialEq, Debug)]
pub enum InputButton {
    A,
    K,
    S,
    T,
    N,
    H,
    M,
    Y,
    R,
    Point,
    W,
    Line,
    Enter,
    Send,
}

#[derive(Clone, PartialEq, Debug)]
pub enum Dire {
    C,
    L,
    U,
    R,
    D,
}

fn char_to_keys(c: char) -> Option<Vec<(InputButton, Dire)>> {
    Some(match c {
        'ァ' => vec![(InputButton::A, Dire::C), (InputButton::Point, Dire::C)],
        'ア' => vec![(InputButton::A, Dire::C)],
        'ィ' => vec![(InputButton::A, Dire::L), (InputButton::Point, Dire::C)],
        'イ' => vec![(InputButton::A, Dire::L)],
        'ゥ' => vec![(InputButton::A, Dire::U), (InputButton::Point, Dire::C)],
        'ウ' => vec![(InputButton::A, Dire::U)],
        'ェ' => vec![(InputButton::A, Dire::R), (InputButton::Point, Dire::C)],
        'エ' => vec![(InputButton::A, Dire::R)],
        'ォ' => vec![(InputButton::A, Dire::D), (InputButton::Point, Dire::C)],
        'オ' => vec![(InputButton::A, Dire::D)],
        'カ' => vec![(InputButton::K, Dire::C)],
        'ガ' => vec![(InputButton::K, Dire::C), (InputButton::Point, Dire::L)],
        'キ' => vec![(InputButton::K, Dire::L)],
        'ギ' => vec![(InputButton::K, Dire::L), (InputButton::Point, Dire::L)],
        'ク' => vec![(InputButton::K, Dire::U)],
        'グ' => vec![(InputButton::K, Dire::U), (InputButton::Point, Dire::L)],
        'ケ' => vec![(InputButton::K, Dire::R)],
        'ゲ' => vec![(InputButton::K, Dire::R), (InputButton::Point, Dire::L)],
        'コ' => vec![(InputButton::K, Dire::D)],
        'ゴ' => vec![(InputButton::K, Dire::D), (InputButton::Point, Dire::L)],
        'サ' => vec![(InputButton::S, Dire::C)],
        'ザ' => vec![(InputButton::S, Dire::C), (InputButton::Point, Dire::L)],
        'シ' => vec![(InputButton::S, Dire::L)],
        'ジ' => vec![(InputButton::S, Dire::L), (InputButton::Point, Dire::L)],
        'ス' => vec![(InputButton::S, Dire::U)],
        'ズ' => vec![(InputButton::S, Dire::U), (InputButton::Point, Dire::L)],
        'セ' => vec![(InputButton::S, Dire::R)],
        'ゼ' => vec![(InputButton::S, Dire::R), (InputButton::Point, Dire::L)],
        'ソ' => vec![(InputButton::S, Dire::D)],
        'ゾ' => vec![(InputButton::S, Dire::D), (InputButton::Point, Dire::L)],
        'タ' => vec![(InputButton::T, Dire::C)],
        'ダ' => vec![(InputButton::T, Dire::C), (InputButton::Point, Dire::L)],
        'チ' => vec![(InputButton::T, Dire::L)],
        'ヂ' => vec![(InputButton::T, Dire::L), (InputButton::Point, Dire::L)],
        'ッ' => vec![(InputButton::T, Dire::U), (InputButton::Point, Dire::C)],
        'ツ' => vec![(InputButton::T, Dire::U)],
        'ヅ' => vec![(InputButton::T, Dire::U), (InputButton::Point, Dire::L)],
        'テ' => vec![(InputButton::T, Dire::R)],
        'デ' => vec![(InputButton::T, Dire::R), (InputButton::Point, Dire::L)],
        'ト' => vec![(InputButton::T, Dire::D)],
        'ド' => vec![(InputButton::T, Dire::D), (InputButton::Point, Dire::L)],
        'ナ' => vec![(InputButton::N, Dire::C)],
        'ニ' => vec![(InputButton::N, Dire::L)],
        'ヌ' => vec![(InputButton::N, Dire::U)],
        'ネ' => vec![(InputButton::N, Dire::R)],
        'ノ' => vec![(InputButton::N, Dire::D)],
        'ハ' => vec![(InputButton::H, Dire::C)],
        'バ' => vec![(InputButton::H, Dire::C), (InputButton::Point, Dire::L)],
        'パ' => vec![(InputButton::H, Dire::C), (InputButton::Point, Dire::R)],
        'ヒ' => vec![(InputButton::H, Dire::L)],
        'ビ' => vec![(InputButton::H, Dire::L), (InputButton::Point, Dire::L)],
        'ピ' => vec![(InputButton::H, Dire::L), (InputButton::Point, Dire::R)],
        'フ' => vec![(InputButton::H, Dire::U)],
        'ブ' => vec![(InputButton::H, Dire::U), (InputButton::Point, Dire::L)],
        'プ' => vec![(InputButton::H, Dire::U), (InputButton::Point, Dire::R)],
        'ヘ' => vec![(InputButton::H, Dire::R)],
        'ベ' => vec![(InputButton::H, Dire::R), (InputButton::Point, Dire::L)],
        'ペ' => vec![(InputButton::H, Dire::R), (InputButton::Point, Dire::R)],
        'ホ' => vec![(InputButton::H, Dire::D)],
        'ボ' => vec![(InputButton::H, Dire::D), (InputButton::Point, Dire::L)],
        'ポ' => vec![(InputButton::H, Dire::D), (InputButton::Point, Dire::R)],
        'マ' => vec![(InputButton::M, Dire::C)],
        'ミ' => vec![(InputButton::M, Dire::L)],
        'ム' => vec![(InputButton::M, Dire::U)],
        'メ' => vec![(InputButton::M, Dire::R)],
        'モ' => vec![(InputButton::M, Dire::D)],
        'ャ' => vec![(InputButton::Y, Dire::C), (InputButton::Point, Dire::C)],
        'ヤ' => vec![(InputButton::Y, Dire::C)],
        'ュ' => vec![(InputButton::Y, Dire::U), (InputButton::Point, Dire::C)],
        'ユ' => vec![(InputButton::Y, Dire::U)],
        'ョ' => vec![(InputButton::Y, Dire::D), (InputButton::Point, Dire::C)],
        'ヨ' => vec![(InputButton::Y, Dire::D)],
        'ラ' => vec![(InputButton::R, Dire::C)],
        'リ' => vec![(InputButton::R, Dire::L)],
        'ル' => vec![(InputButton::R, Dire::U)],
        'レ' => vec![(InputButton::R, Dire::R)],
        'ロ' => vec![(InputButton::R, Dire::D)],
        'ヮ' => vec![(InputButton::W, Dire::C), (InputButton::Point, Dire::C)],
        'ワ' => vec![(InputButton::W, Dire::C)],
        'ヲ' => vec![(InputButton::W, Dire::L), (InputButton::Point, Dire::C)],
        'ン' => vec![(InputButton::W, Dire::U)],
        'ー' => vec![(InputButton::Line, Dire::C)],
        _ => return None,
    })
}

pub fn string_to_keys(s: &String) -> Option<Vec<(InputButton, Dire)>> {
    let mut keys = Vec::new();
    for c in s.chars() {
        for key in char_to_keys(c)? {
            keys.push(key);
        }
        keys.push((InputButton::Enter, Dire::C));
    }
    keys.push((InputButton::Send, Dire::C));
    Some(keys)
}
